### ISSUE TITLE
Fix Bug: "display" Value in ValueSet Expansion

### ISSUE THREAD

**Issue by NHDR-Teo** [UP-Manila-SILab/PhilHealth-NHDR-IG-Review#40]
There is an issue where some ValueSets, particularly those referencing HL7 terminologies, do not correctly display the "display" field in the expansion. This bug needs to be fixed to ensure correct representation of ValueSet codes in the IG.

**Comment by nhdr-gianb** [comment]
Just to add details to this issue, an inconsistency occurs whenever a ValueSet gets expanded, even if we're using a CodeSystem from [HL7's Terminology Service](https://terminology.hl7.org/). The resulting table displayed on our IG displays the columns "Code", "System", "Display", and "Definition", as such:

![Image](https://github.com/user-attachments/assets/53e0d3bb-e619-44f6-98c2-aab99a807df4)
However the Display column is empty.

In some cases, it even pulls the display from a different column, for example, a different language as such:
![Image](https://github.com/user-attachments/assets/f73a3286-84a9-4ce9-b8e1-c79d87b42cd3)
even if the referenced CodeSystem includes a proper Display column:
![Image](https://github.com/user-attachments/assets/89ebd330-b20a-48b7-ab73-11c82052cabe)

While in other cases, they properly display the Display column:
![Image](https://github.com/user-attachments/assets/7d5f4bcd-2e7c-4ef3-8fbf-54aca100da79)

And lastly, we also found that when using our local CodeSystems, the ValueSet properly expands when we set the language of the CodeSystem to "en" or "en-US", as can be seen here:
![Image](https://github.com/user-attachments/assets/81f80fca-60bc-4483-be0a-acff93ff1ff6)

**Comment by upmsilab** [comment]
@johnscarter - Hi John, do we have an update on this issue? Thank you!

**Comment by NHDR-Quin** [comment]
Hi @upmsilab, we are still waiting for the FHIR Mapping team to provide the value sets for the extended elements, as they are still in the process of consolidating them (e.g., PH_Procedure.IllnessClass extension).

Regarding the value sets that reference HL7 terminologies (as @nhdr-gianb mentioned above) that are not displaying correctly, we’ve attempted various configurations based on the documentation, but we were unsuccessful. However, since these value sets are from HL7 Terminologies, we are unsure how they are configured unless we create them as our own local custom value sets instead of directly referencing HL7. We are still waiting to see if @johnscarter can fix this bug.

**Comment by johnscarter** [comment]
I have raised this issue in the FHIR chat... [#IG creation > Value set Display column empty](https://chat.fhir.org/#narrow/channel/179252-IG-creation/topic/Value.20set.20Display.20column.20empty)

**Comment by johnscarter** [comment]
In the FHIR chat above, the issue has been acknowledged by Grahame Grieve, and he is investigating. There is no action for us to take. Although the IG doesn't look as good with this bug, it does not prevent implementation. Therefore @gpvillanuevasilab  maybe consider closing this issue.

**Comment by gpvillanuevasilab** [comment]
> In the FHIR chat above, the issue has been acknowledged by Grahame Grieve, and he is investigating. There is no action for us to take. Although the IG doesn't look as good with this bug, it does not prevent implementation. Therefore [@gpvillanuevasilab](https://github.com/gpvillanuevasilab) maybe consider closing this issue.

Can we close the ticket now sir @NHDR-Teo @nhdr-gianb

**Comment by NHDR-Teo** [comment]
We'll keep this ticket open for tracking purposes and follow up as needed until it's resolved.

**Comment by NHDR-Quin** [comment]
Grahame Grieve commented on our concern earlier, stating that a new update would fix the issue. However, after updating SUSHI to version 3.15, the issue remains unresolved.

![Image](https://github.com/user-attachments/assets/8416492a-7821-48f5-8c15-82462200bb42)

**Comment by johnscarter** [comment]
> Grahame Grieve commented on our concern earlier, stating that a new update would fix the issue. However, after updating SUSHI to version 3.15, the issue remains unresolved.
> 
> ![Image](https://github.com/user-attachments/assets/8416492a-7821-48f5-8c15-82462200bb42)

I think the fix will appear in an update to IG-Publisher, not SUSHI. To get the latest version of IG Publisher, I run the _updatePublisher script.

**Comment by gpvillanuevasilab** [comment]
Update: The bug was already acknowledged by HL7 and they are working on it. We will just monitor if there are changes.

**Comment by upmsilab** [comment]
PHIC @NHDR-Quin and @johnscarter - to check if the bug was already addressed.

**Comment by johnscarter** [comment]
This is now working correctly. Closing.

**Comment by upmsilab** [comment]
PHIC to provide screenshots and documentation of other bugs that they encountered. The team decided to reopen the issue.

**Comment by nhdr-gianb** [comment]
The SUSHI v15 update fixed most of the issue's occurrence, but not all of them. We still have some ValueSets that are displaying a different column under **Display (en-US)**.

For example:

Here we have `ContactEntityType` vs. `ContactRelationship`

![Image](https://github.com/user-attachments/assets/6b6b8437-be90-4afb-9e6d-3ee0dcc5ff69) 

![Image](https://github.com/user-attachments/assets/01209be7-ac03-48ae-ac26-ee7b3b9cb8e5)

As we can see, ContactEntityType properly displays the English display column, while ContactRelationship does not.

Looking at the fsh files, we can see they have a similar metadata:

![Image](https://github.com/user-attachments/assets/aa8e728b-73de-42fa-b8ac-79b0d5f453b9)

![Image](https://github.com/user-attachments/assets/ab9b07e0-9787-4f08-ae0e-926320f02191)

Aside from **[ContactRelationshipVS](https://build.fhir.org/ig/UP-Manila-SILab/PhilHealth-NHDR-IG-Review/ValueSet-ContactRelationshipVS.html)**, we also noticed this issue still persists in **[DiagnosticServiceSection](https://build.fhir.org/ig/UP-Manila-SILab/PhilHealth-NHDR-IG-Review/ValueSet-DiagnosticServiceSectionVS.html)**, **[RelationshipType](https://build.fhir.org/ig/UP-Manila-SILab/PhilHealth-NHDR-IG-Review/ValueSet-RelationshipTypeCS.html)**, **[SexVS](https://build.fhir.org/ig/UP-Manila-SILab/PhilHealth-NHDR-IG-Review/ValueSet-SexVS.html)**, and **[SpecimenTypeVS](https://build.fhir.org/ig/UP-Manila-SILab/PhilHealth-NHDR-IG-Review/ValueSet-SpecimenTypeVS.html)**.

**Comment by nhdr-gianb** [comment]
I looked over the ValueSets with issues again and noticed that some of them actually have mixed German and English displays. Then I noticed something that might be important to note.

In the **[SpecimenTypeVS](https://build.fhir.org/ig/UP-Manila-SILab/PhilHealth-NHDR-IG-Review/ValueSet-SpecimenTypeVS.html)**, only the first two entries display the German column.
![Image](https://github.com/user-attachments/assets/777a0601-dfdd-414f-8ee4-2b108aa828ca)
So I looked over the source CodeSystem and noticed that only the first two entries contains text in the German column.
![Image](https://github.com/user-attachments/assets/77a12717-fcf5-48f7-8b0f-16ca07515927)

Same thing with the second example you linked in the FHIR chat for **[DiagnosticServiceSectionVS](https://build.fhir.org/ig/UP-Manila-SILab/PhilHealth-NHDR-IG-Review/ValueSet-DiagnosticServiceSectionVS.html)**, I noticed that there *are* some rows that properly load the English display, namely the **Cytogenetics**, **Diagnostic Imaging**, and **Bedside ICU Monitoring**.
![Image](https://github.com/user-attachments/assets/faa31888-8e6d-4358-a770-3783bcf35281)


Looking over the source CodeSystem again, I found that those are rows that *don't* have any entry in the German column.
![Image](https://github.com/user-attachments/assets/b1e962eb-f5d0-4c88-8dee-6e765ca260c8)


Based on these observations, I think the both SUSHI and the IG-Publisher might be prioritizing other language columns before defaulting to the English or en-US column.

**Comment by upmsilab** [comment]
Based on the latest update - The bug was already fixed (Gian)
